### PR TITLE
Support transaction mechanism

### PR DESCRIPTION
**Pull request by moznion**
ref #6 

This pull-request contains following changes.

## Supports following methods;

- `setAutoCommit(boolean isAutoCommit)`: Sets auto-commit mode to connection which is held by an instance of ORM
- `transactionBegin()`: Begins transaction with saving original auto-commit mode
- `transactionCommit()`: Commits the current transaction.
- `transactionRollback()`: Rollbacks the current transaction.
- `createTransactionScope()`: Dispense a transaction scope instance.

## <s>Provides a functional interface;</s>

- <s>`RunnableStatement`: Runnable interface for statement (this interface's method can throw SQLException). For `transactionScope`.</s>

### CODE REVIEW

**Comment by tokuhirom** [comment]
Why did you add the 'transaction' prefix?

**Comment by moznion** [comment]
Ah, these were named in reference to Teng's API.
Do you think these prefix are unnecessary?
(From my perspective, maybe `transactionScope`'s one is is better than nothing)

**Comment by tokuhirom** [comment]
Okay, but I think we need to review transactionmanager first.

**Comment by moznion** [comment]
Got it

**Comment by moznion** [comment]
This p-r is no longer mergeable. So just close this.

**Pull request closed without merging**
